# Generated by Django 5.1.7 on 2025-04-05 13:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_cliente_data_nascimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, max_length=255, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
