# Generated by Django 5.1.7 on 2025-04-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_produto_ativo_produto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilograma'), ('litro', 'Litro'), ('m', 'Metro'), ('pacote', 'Pacote'), ('caixa', 'Caixa'), ('outro', 'Outro')], default='un', max_length=32),
        ),
    ]
