# Generated by Django 5.1.7 on 2025-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_produto_quantidade_estoque_produto_unidade_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
