# Generated by Django 5.1.7 on 2025-04-13 12:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_produto_preco_custo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda')], max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço unitário desta movimentação', max_digits=10)),
                ('novo_preco_custo', models.DecimalField(blank=True, decimal_places=2, help_text='Novo preço de custo (opcional, para compra)', max_digits=10, null=True)),
                ('novo_preco_venda', models.DecimalField(blank=True, decimal_places=2, help_text='Novo preço de venda (opcional, para compra)', max_digits=10, null=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente (para venda)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.cliente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='crm.produto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
