name: Django CI/CD - Deploy para Render

on:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar migrações do banco de dados
        run: |
          python manage.py migrate --noinput

      - name: Rodar testes
        run: |
          python manage.py test

      - name: Criar arquivos estáticos
        run: |
          python manage.py collectstatic --noinput

      - name: Deploy para Render
        uses: render-examples/django-render-action@v1
        with:
          render_api_key: ${{ secrets.RENDER_API_KEY }} 
          render_service_id: ${{ secrets.RENDER_SERVICE_ID }} 