name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: "config.django.local"
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DJANGO_DEBUG: True
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      POSTGRES_NAME: ${{ secrets.POSTGRES_NAME }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.17
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.17
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Debug Environment Variables
        run: |
          echo "DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE"
          echo "POSTGRES_NAME: ${{ secrets.POSTGRES_NAME }}"
          echo "POSTGRES_USER: ${{ secrets.POSTGRES_USER }}"
          echo "POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}"
          echo "POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}"
          echo "POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}"
      - name: Test with Django
        run: |
          export DJANGO_SETTINGS_MODULE="${{ env.DJANGO_SETTINGS_MODULE }}"
          export POSTGRES_NAME="${{ secrets.POSTGRES_NAME }}"
          export POSTGRES_USER="${{ secrets.POSTGRES_USER }}"
          export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
          export POSTGRES_HOST="${{ secrets.POSTGRES_HOST }}"
          export POSTGRES_PORT="${{ secrets.POSTGRES_PORT }}"
          python manage.py test
